from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported
import os

# 1. Configuration & Model Loading
max_seq_length = 2048 # Max context window
dtype = None # Auto-detect based on hardware
load_in_4bit = True # CRITICAL for 6GB VRAM GPUs

print("Loading Qwen model in 4-bit...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# 2. Setup LoRA Adapters
# This is where the magic happens: we only train ~1% of the model
print("Injecting LoRA adapters...")
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank of the adapter
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, # Optimized for Unsloth
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# 3. Data Preparation
print("Loading and formatting dataset...")
# ChatML format string specifically for Qwen models
prompt_template = """<|im_start|>user
{prompt}<|im_end|>
<|im_start|>assistant
{completion}<|im_end|>"""

EOS_TOKEN = tokenizer.eos_token

def formatting_prompts_func(examples):
    prompts = examples["prompt"]
    completions = examples["completion"]
    texts = []
    for p, c in zip(prompts, completions):
        text = prompt_template.format(prompt=p, completion=c) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts }

# Load the dataset generated by our Rust backend
dataset_path = "../dataset.jsonl"
if not os.path.exists(dataset_path):
    raise FileNotFoundError(f"Dataset not found at {dataset_path}. Please use the terminal first to generate data.")

dataset = load_dataset("json", data_files={"train": dataset_path}, split="train")
dataset = dataset.map(formatting_prompts_func, batched = True)

# 4. Training Parameters
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # We run for exactly 60 steps for our first test
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit", # 8-bit optimizer to save VRAM
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", 
    ),
)

# 5. Execute Training
print("Starting the Fine-Tuning process...")
trainer_stats = trainer.train()

# 6. Save the new "Brain"
print("Training Complete! Saving model...")
model.save_pretrained("lora_adapter")
tokenizer.save_pretrained("lora_adapter")
print("Success! Custom adapter saved in /training-pipeline/lora_adapter")